packages:
  - packages/*
  - playground/*
  - '!playground/nuxt'
  - docs

catalog:
  '@vue/compiler-sfc': ^3.4.31
  '@vue/compiler-core': ^3.4.31
  '@vue/compiler-dom': ^3.4.31
  '@vue/shared': ^3.4.31
  '@vue/language-core': 2.0.24
  vue: ^3.4.31
  vue-tsc: 2.0.24
  unplugin: ^1.11.0
  vite: ^5.3.3
