# eslint yml/sort-keys: 'error'

catalog:
  '@vue/compiler-core': ^3.4.36
  '@vue/compiler-dom': ^3.4.36
  '@vue/compiler-sfc': ^3.4.36
  '@vue/language-core': 2.0.29
  '@vue/reactivity': ^3.4.36
  '@vue/runtime-core': ^3.4.36
  '@vue/runtime-dom': ^3.4.36
  '@vue/shared': ^3.4.36
  unplugin: ^1.12.0
  vite: ^5.4.0
  vue: ^3.4.36
  vue-tsc: 2.0.29
packages:
  - packages/*
  - playground/*
  - '!playground/nuxt'
  - docs
